_wandb:
    value:
        cli_version: 0.25.1
        e:
            zqu0q4cd9o0zkpwbxn77d03xqf6z026d:
                args:
                    - --config-name
                    - config_ws.yaml
                codePath: encoder_survivalhead.py
                codePathLocal: encoder_survivalhead.py
                cpu_count: 14
                cpu_count_logical: 14
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "832314445824"
                        used: "22071488512"
                email: francisco.sa.couto42@gmail.com
                executable: /nas-ctm01/homes/fmferreira/.conda/envs/ctClip/bin/python
                git:
                    commit: 1d4772e6730b0d6447fb3d427a1ade8000d14402
                    remote: git@github.com:franciscosacouto/AI4LUNGS.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-ebc81d87-c625-5198-1983-b60cdd582349
                host: 01.ctm-deep-10
                memory:
                    total: "118158553088"
                os: Linux-6.8.0-106-generic-x86_64-with-glibc2.39
                program: /nas-ctm01/homes/fmferreira/AI4LUNGS/encoder_survivalhead.py
                python: CPython 3.9.25
                root: .
                slurm:
                    cluster_name: (null)
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "14"
                    gtids: "0"
                    job_account: scholar
                    job_cpus_per_node: "14"
                    job_end_time: "1775483672"
                    job_gid: "1000000"
                    job_id: "24478"
                    job_name: radiofrozen
                    job_nodelist: 01.ctm-deep-10
                    job_num_nodes: "1"
                    job_partition: gpu_min80gb
                    job_qos: gpu_min80gb
                    job_start_time: "1774878872"
                    job_uid: "1000262"
                    job_user: fmferreira
                    jobid: "24478"
                    localid: "0"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: 01.ctm-deep-10
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /nas-ctm01/homes/fmferreira/AI4LUNGS
                    submit_host: ctm-login-01.inesctec.pt
                    task_pid: "92848"
                    tasks_per_node: "14"
                    topology_addr: 01.ctm-deep-10
                    topology_addr_pattern: node
                startedAt: "2026-03-30T13:54:58.539437Z"
                writerId: zqu0q4cd9o0zkpwbxn77d03xqf6z026d
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.25
        t:
            "1":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 63
                - 71
                - 80
                - 103
                - 106
            "2":
                - 1
                - 5
                - 9
                - 11
                - 41
                - 49
                - 50
                - 53
                - 63
                - 71
                - 80
                - 103
                - 106
            "3":
                - 7
                - 13
                - 16
                - 66
            "4": 3.9.25
            "5": 0.25.1
            "6": 4.57.6
            "12": 0.25.1
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 100
learning_rate:
    value: 0.0001
model_type:
    value: MLP_Cox
